name: Deploy
description: Deploy

inputs:
  aws_access_key_id:
    description: AWS_ACCESS_KEY_ID
    required: true
  aws_secret_access_key:
    description: AWS_SECRET_ACCESS_KEY
    required: true
  aws_region:
    description: AWS_REGION
    required: true
  bucket_name:
    description: AWS_REGION
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@master
      with:
        name: buid-artifact
        path: vue/dist

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ inputs.bucket_name }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: ${{ inputs.aws_region }}
        SOURCE_DIR: "vue/dist"
